blank_issues_enabled: false
contact_links:
  - name: Support via Discord
    url: https://discord.gg/M6BvZn5
    about: Chat with users and devs on support and setup related topics.
  - name: Support via Reddit
    url: https://reddit.com/r/Sportarr
    about: Discuss and search through support topics.
  - name: Support via Forums
    url: https://forums.sportarr.tv/
    about: Discuss and search through support topics.
  - name: Support via IRC
    url: https://web.libera.chat/?channels=#sportarr
    about: Chat with users and devs on support and setup related topics.