blank_issues_enabled: false
contact_links:
  - name: Support via Discord
    url: https://discord.gg/YjHVWGWjjG
    about: Chat with users and devs on support and setup related topics.
  - name: GitHub Discussions
    url: https://github.com/Sportarr/Sportarr/discussions
    about: Discuss and search through support topics.
